baseURL = 'https://nbenatti.github.io/'
locale = 'en-gb'
title = 'Nicolas Benatti'
disableKinds = ["taxonomy", "term"]

[params]
  author      = "Nicolas Benatti"
  bio         = "Researcher and engineer. I build things and write about them."
  avatar      = "/images/me.png"
  description = "Nicolas Benatti's Web corner"

  [params.social]
    github        = "https://github.com/nicolasbenatti"
    email         = "mailto:nicolas.benatti@mail.polimi.it"
    twitter       = ""          # leave empty to hide
    linkedin      = "https://www.linkedin.com/in/nicolas-benatti"
    orcid         = "https://orcid.org/0009-0007-8379-9733"
    googlescholar = "https://scholar.google.com/citations?user=Cb9N83MAAAAJ&hl=en"

[[menus.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menus.main]]
  name   = "Projects"
  url    = "/projects/"
  weight = 2

[[menus.main]]
  name   = "Publications"
  url    = "/publications/"
  weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
